apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-account
  namespace: apps
  labels:
    app: repo-account
    type: backends
spec:
  # replicas: 1 # managed by hpa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: repo-account
  template:
    metadata:
      labels:
        app: repo-account
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090" 
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: repo-account
          image: ghcr.io/therayquaza/newsbro/repo-account:repo-account-v1.2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: repo-account-config
            - secretRef:
                name: oidc-secrets
            - secretRef:
                name: repo-account-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
