apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: capacitor-next
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: flux-system/capacitor-next
