---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: kv
  labels:
    component: kv
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
