---
# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo
  namespace: qdrant
spec:
  interval: 10m0s
  type: default
  url: https://qdrant.github.io/qdrant-helm
  provider: generic
