---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 5m
  chart:
    spec:
      chart: qdrant
      version: 1.15.4
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: qdrant
  valuesFrom:
    - kind: ConfigMap
      name: qdrant-values
      #namespace: qdrant
      valuesKey: values.yaml
