---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: helm-chart
  namespace: minio
spec:
  chart: minio
  version: 5.4.0
  sourceRef:
    kind: HelmRepository
    name: helm-repo
  interval: 1m0s
  reconcileStrategy: ChartVersion
  valuesFiles:
    - values.yaml
