---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-secret
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-new # bug from sts chart that uses release name, not my override
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootUser: "{{ .rootUser }}"
        rootPassword: "{{ .rootPassword }}"
  dataFrom:
    - extract:
        key: minio/credentials
        property: rootUser
    - extract:
        key: minio/credentials
        property: rootPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: centralized-minio-users
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: centralized-minio-users
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        console: |
          username={{ .console.username }}
          password={{ .console.password }}
          disabled={{ .console.disabled }}
          policies={{ .console.policies }}
          setPolicies={{ .console.setPolicies }}
        minio: |
          username={{ .minio.username }}
          password={{ .minio.password }}
          disabled={{ .minio.disabled }}
          policies={{ .minio.policies }}
          setPolicies={{ .minio.setPolicies }}
  dataFrom:
    # Console user
    - extract:
        key: minio/users/console
        property: username
      name: console.username
    - extract:
        key: minio/users/console
        property: password
      name: console.password
    - extract:
        key: minio/users/console
        property: disabled
      name: console.disabled
    - extract:
        key: minio/users/console
        property: policies
      name: console.policies
    - extract:
        key: minio/users/console
        property: setPolicies
      name: console.setPolicies
    # Minio user
    - extract:
        key: minio/users/minio
        property: username
      name: minio.username
    - extract:
        key: minio/users/minio
        property: password
      name: minio.password
    - extract:
        key: minio/users/minio
        property: disabled
      name: minio.disabled
    - extract:
        key: minio/users/minio
        property: policies
      name: minio.policies
    - extract:
        key: minio/users/minio
        property: setPolicies
      name: minio.setPolicies
