---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-secret
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-root-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootUser: "{{ .rootUser }}"
        rootPassword: "{{ .rootPassword }}"
  dataFrom:
    - extract:
        key: minio/credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: centralized-minio-users
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: centralized-minio-users
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        console: |
          username={{ .console.username }}
          password={{ .console.password }}
          disabled={{ .console.disabled }}
          policies={{ .console.policies }}
          setPolicies={{ .console.setPolicies }}
        minio: |
          username={{ .minio.username }}
          password={{ .minio.password }}
          disabled={{ .minio.disabled }}
          policies={{ .minio.policies }}
          setPolicies={{ .minio.setPolicies }}
  dataFrom:
    - extract:
        key: minio/users/console
        property: .
      # loads all fields as `.console.*`
    - extract:
        key: minio/users/minio
        property: .
