---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-secret
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-new # bug from sts chart that uses release name, not my override
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootUser: "{{ .rootUser }}"
        rootPassword: "{{ .rootPassword }}"
  dataFrom:
    - extract:
        key: minio/credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: centralized-minio-users
  namespace: minio
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: centralized-minio-users
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        console: |
          username: "{{ .console_username }}"
          password: "{{ .console_password }}"
          disabled: "{{ .console_disabled }}"
          policies: "{{ .console_policies }}"
          setPolicies: "{{ .console_setPolicies }}"
        minio: |
          username: "{{ .minio_username }}"
          password: "{{ .minio_password }}"
          disabled: "{{ .minio_disabled }}"
          policies: "{{ .minio_policies }}"
          setPolicies: "{{ .minio_setPolicies }}"
  data:
    - secretKey: console_username
      remoteRef:
        key: minio/users/console
        property: username
    - secretKey: console_password
      remoteRef:
        key: minio/users/console
        property: password
    - secretKey: console_disabled
      remoteRef:
        key: minio/users/console
        property: disabled
    - secretKey: console_policies
      remoteRef:
        key: minio/users/console
        property: policies
    - secretKey: console_setPolicies
      remoteRef:
        key: minio/users/console
        property: setPolicies
    - secretKey: minio_username
      remoteRef:
        key: minio/users/minio
        property: username
    - secretKey: minio_password
      remoteRef:
        key: minio/users/minio
        property: password
    - secretKey: minio_disabled
      remoteRef:
        key: minio/users/minio
        property: disabled
    - secretKey: minio_policies
      remoteRef:
        key: minio/users/minio
        property: policies
    - secretKey: minio_setPolicies
      remoteRef:
        key: minio/users/minio
        property: setPolicies
