kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-values
  namespace: minio
data:
  values.yaml: |
    # https://artifacthub.io/packages/helm/bitnami/minio?modal=values
    auth:
      rootUser: admin
      rootPassword: minio123456

    users:
      - accessKey: console
        secretKey: console123
        policy: consoleAdmin

      - accessKey: minio
        secretKey: minio123
        policy: consoleAdmin

    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path

    replicas: 4
    drivesPerNode: 1

    minioAPIPort: 9000
    minioConsolePort: 9001
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      type: ClusterIP
      port: 9001

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

    securityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001

    # https://artifacthub.io/packages/helm/bitnami/minio?modal=values&path=defaultBuckets
    # defaultBuckets: "datalake,json-data,parking-events" this is standalone only 
    mode: distributed

    buckets:
      - name: parking-events
        policy: none
        purge: false
      - name: alert-events
        policy: none
        purge: false
      - name: datalake
        policy: none
        purge: false
      - name: json-data
        policy: none
        purge: false

    ingress:
      enabled: false

    consoleIngress:
      enabled: true
      ingressClassName: traefik
      path: /
      hosts:
        - minio.localhost

    metrics:
      serviceMonitor:
        includeNode: true
        enabled: true
        namespace: minio
