kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-values
  namespace: minio
data:
  values.yaml: |
    # https://artifacthub.io/packages/helm/bitnami/minio?modal=values
    auth:
      existingSecret: minio-root-secret

    usersExistingSecrets:
      - centralized-minio-users

    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path

    replicas: 4
    drivesPerNode: 1

    minioAPIPort: 9000
    minioConsolePort: 9001
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      type: ClusterIP
      port: 9001

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

    securityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001

    mode: distributed

    buckets:
      - name: mlflow
        policy: none
        purge: false
      - name: papers
        policy: none
        purge: false

    ingress:
      enabled: true
      ingressClassName: traefik
      path: /
      hosts:
        - minio-svc.localhost

    consoleIngress:
      enabled: true
      ingressClassName: traefik
      path: /
      hosts:
        - minio.localhost

    # metrics:
    #   serviceMonitor:
    #     includeNode: true
    #     enabled: true
    #     namespace: minio
