---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helm-release-operator
  namespace: redis
spec:
  interval: 10m0s
  chart:
    spec:
      chart: redis-operator
      version: 3.2.8
      sourceRef:
        kind: HelmRepository
        name: helm-repo-operator
        namespace: redis
  values:
    imageCredentials: {}

    updateStrategy:
      type: RollingUpdate

    replicas: 1

    nameOverride: ""
    fullnameOverride: ""
    namespace: redis

    serviceAccount:
      create: true
      annotations: {}
      name: ""

    service:
      type: ClusterIP
      port: 9710

    container:
      port: 9710

    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

