---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/capacitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
