---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 1m
  path: ./k8s/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
