---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 1m
  path: ./k8s/qdrant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
