---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  path: ./k8s/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
