---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1m
  path: ./k8s/vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
