---
# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo-pgadmin
  namespace: postgres
spec:
  interval: 10m0s
  type: default
  url: https://helm.runix.net
  provider: generic
