---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: postgres
spec:
  interval: 10m0s
  chart:
    spec:
      chart: pgadmin4
      version: 1.50.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo-pgadmin
        namespace: postgres
  valuesFrom:
    - kind: ConfigMap
      name: pgadmin-values
      valuesKey: values.yaml
