kind: ConfigMap
apiVersion: v1
metadata:
  name: pgadmin-values
  namespace: postgres
data:
  values.yaml: |
    global:
      imageRegistry: ""
      imagePullSecrets: []

    replicaCount: 1

    image:
      registry: docker.io
      repository: dpage/pgadmin4
      tag: ""
      pullPolicy: IfNotPresent
    imagePullSecrets: []

    annotations: {}
    revisionHistoryLimit: 10
    commonLabels: {}
    priorityClassName: ""

    service:
      type: ClusterIP
      clusterIP: ""
      loadBalancerIP: ""
      port: 80
      targetPort: 80
      portName: http
      annotations: {}

    serviceAccount:
      create: false
      annotations: {}
      name: ""
      automountServiceAccountToken: false

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    preferences:
      enabled: false
      existingConfigMap: ""
      data:
        misc:user_interface:theme: dark

    networkPolicy:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations: {}
      labels: {}
      hosts:
        - host: pgadmin.localhost
          paths:
            - path: /
              pathType: Prefix
      tls: []

    extraConfigmapMounts: []
    extraSecretMounts: []
    extraVolumeMounts: []

    secretKeys:
      pgadminPasswordKey: password

    envVarsFromConfigMaps: []
    envVarsFromSecrets: []

    persistentVolume:
      enabled: true
      annotations: {}

      accessModes:
        - ReadWriteOnce

      size: 10Gi
      subPath: ""

    extraVolumes: []

    securityContext:
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050

    containerSecurityContext:
      enabled: false
      allowPrivilegeEscalation: false

    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

    startupProbe:
      failureThreshold: 30
      periodSeconds: 2

    containerPorts:
      http: 80

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
