---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka
  labels:
    app: kafka-operator
spec:
  releaseName: kafka-operator
  interval: 10m0s
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.43.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    watchAnyNamespace: true
    tolerations: []
    resources:
      limits:
        memory: 384Mi
        cpu: 1000m
      requests:
        memory: 384Mi
        cpu: 200m
# kubectl set env deployment/strimzi-cluster-operator STRIMZI_KUBERNETES_VERSION="major=1,minor=33"
# https://github.com/strimzi/strimzi-kafka-operator/issues/11386
