---
# https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  instances: 1
  imagePullPolicy: IfNotPresent
  bootstrap:
    initdb: {}
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  managed:
    roles:
    - name: admin
      ensure: present
      login: true
      superuser: true
      passwordSecret:
        name: admin-db-secret
    - name: mlflow
      ensure: present
      login: true
      passwordSecret:
        name: mlflow-db-secret
    - name: repo-account
      ensure: present
      login: true
      passwordSecret:
        name: repo-account-db-secret
    - name: repo-article
      ensure: present
      login: true
      passwordSecret:
        name: repo-article-db-secret
  storage:
    size: 10Gi
    storageClass: local-path
    resizeInUseVolumes: true
    pvcTemplate:
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  imageName: ghcr.io/cloudnative-pg/postgresql:13.6
