---
kind: Secret
apiVersion: v1
metadata:
  name: mlflow-db-secret
  namespace: postgres
type: Opaque
data:
  username: bWxmbG93
  password: bXlzdXBlcnNlY3JldHBhc3N3b3Jk
---
kind: Secret
apiVersion: v1
metadata:
  name: repo-account-db-secret
  namespace: postgres
type: Opaque
data:
  username: cmVwby1hY2NvdW50
  password: bXlzdXBlcnNlY3JldHBhc3N3b3Jk
