---
# https://fluxcd.io/flux/components/helm/helmreleases/
# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: postgres
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
      valuesKey: values.yaml
