---
# https://fluxcd.io/flux/components/helm/helmreleases/
# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: postgres
  values:
    replicaCount: 1

    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      tag: "1.26.0"

    imagePullSecrets: []

    hostNetwork: false
    dnsPolicy: ""

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1

    crds:
      create: true

    webhook:
      port: 9443
      mutating:
        create: true
        failurePolicy: Fail
      validating:
        create: true
        failurePolicy: Fail
      livenessProbe:
        initialDelaySeconds: 3
      readinessProbe:
        initialDelaySeconds: 3
      startupProbe:
        failureThreshold: 6
        periodSeconds: 5

    config:
      create: true
      name: cnpg-controller-manager-config
      secret: false
      clusterWide: true
      data: {}
      maxConcurrentReconciles: 10

    serviceAccount:
      create: true
      name: ""

    rbac:
      create: true
      aggregateClusterRoles: false

    commonAnnotations: {}
    podAnnotations: {}
    podLabels: {}

    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 10001
      runAsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - "ALL"

    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      # fsGroup: 2000

    priorityClassName: ""

    service:
      type: ClusterIP
      name: cnpg-webhook-service
      port: 443
      ipFamilyPolicy: ""
      ipFamilies: []

    resources:
      requests:
        memory: "256Mi"
        cpu: "125m"
      limits:
        memory: "1Gi"
        cpu: "250m"

    nodeSelector: {}

    topologySpreadConstraints: []
    tolerations: []
    affinity: {}

    monitoring:
      podMonitorEnabled: false
      podMonitorMetricRelabelings: []
      podMonitorRelabelings: []
      podMonitorAdditionalLabels: {}

      grafanaDashboard:
        create: false
        namespace: ""
        configMapName: "cnpg-grafana-dashboard"
        sidecarLabel: "grafana_dashboard"
        sidecarLabelValue: "1"
        labels: {}
        annotations: {}

    # Default monitoring queries
    monitoringQueriesConfigMap:
      name: cnpg-default-monitoring
      queries: ""
