---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-creds
  namespace: postgres
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        MINIO_ACCESS_KEY: "{{ .user }}"
        MINIO_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres/minio
