definitions:
  repo_article_src_api_dto.ArticleCreateRequest:
    properties:
      abstract:
        type: string
      category:
        type: string
      link:
        type: string
      subcategory:
        type: string
      title:
        type: string
    required:
    - category
    - link
    - subcategory
    - title
    type: object
  repo_article_src_api_dto.ArticleUpdateRequest:
    properties:
      abstract:
        type: string
      category:
        type: string
      id:
        type: integer
      link:
        type: string
      subcategory:
        type: string
      title:
        type: string
    required:
    - id
    type: object
  repo_article_src_data_models.Article:
    properties:
      abstract:
        type: string
      category:
        type: string
      created_at:
        type: string
      id:
        type: integer
      link:
        type: string
      subcategory:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /articles:
    get:
      description: Get a list of articles with optional filtering and pagination
      parameters:
      - description: Filter by category
        in: query
        name: category
        type: string
      - description: Filter by subcategory
        in: query
        name: subcategory
        type: string
      - description: Search in title and abstract
        in: query
        name: search
        type: string
      - default: 10
        description: Limit number of results
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Get all articles
      tags:
      - Articles
    post:
      consumes:
      - application/json
      description: Create a new article with the provided data
      parameters:
      - description: Article data
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/repo_article_src_api_dto.ArticleCreateRequest'
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/repo_article_src_data_models.Article'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Create a new article
      tags:
      - Articles
  /articles/{id}:
    delete:
      description: Delete an article by ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Delete article
      tags:
      - Articles
    get:
      description: Get a specific article by its ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo_article_src_data_models.Article'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Get article by ID
      tags:
      - Articles
    put:
      consumes:
      - application/json
      description: Update an existing article by ID
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - description: Article update data
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/repo_article_src_api_dto.ArticleUpdateRequest'
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo_article_src_data_models.Article'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Update article
      tags:
      - Articles
  /articles/categories:
    get:
      description: Get all available article categories
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Get categories
      tags:
      - Articles
  /articles/subcategories:
    get:
      description: Get subcategories for a specific category or all subcategories
      parameters:
      - description: Filter subcategories by category
        in: query
        name: category
        type: string
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - JWT: []
      summary: Get subcategories
      tags:
      - Articles
swagger: "2.0"
