---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: srvc-scrapping-job
  namespace: apps
  labels:
    app: srvc-scrapping
    type: backends
spec:
  # 9 AM and 6 PM every day
  schedule: "0 9,18 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: srvc-scrapping
        spec:
          imagePullSecrets:
            - name: pull-secret
          restartPolicy: OnFailure
          containers:
            - name: srvc-scrapping
              image: ghcr.io/therayquaza/newsbro/srvc-scrapping:srvc-scrapping-v1.1.0
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080
                  name: http
              envFrom:
                - configMapRef:
                    name: srvc-scrapping-config
                - secretRef:
                    name: srvc-scrapping-secrets
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "200m"
