---
# https://fluxcd.io/flux/components/helm/helmreleases/
# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  interval: 10m0s
  chart:
    spec:
      chart: mlflow
      version: 
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: mlflow
  valuesFrom:
    - kind: ConfigMap
      name: mlflow-values
      valuesKey: values.yaml
