---
# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo
  namespace: mlflow
spec:
  interval: 10m0s
  type: default
  url: https://community-charts.github.io/helm-charts
  provider: generic
