---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: apps
resources:
  - namespace.yaml
  - repo-account
  - repo-article
  - pull-secrets.yaml
  - certificate.yaml
  - oidc-secrets.yaml
