apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secrets
  namespace: apps
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: oidc-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: oidc
