---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: apps
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "VGhlUmF5cXVhemE6Z2hwX2hLMHp0RlppZE1OU0ZVMmlSQklrdGFiMlVYb3VzQjRDVVp5bw=="
        }
      }
    }
type: kubernetes.io/dockerconfigjson
