---
type: kubernetes.io/dockerconfigjson
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: apps
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: docker/ghcr
        property: auth
  target:
    name: pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ .auth | toString }}"
              }
            }
          }
