---
# https://fluxcd.io/flux/components/source/helmcharts
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: helm-chart
  namespace: vault
spec:
  chart: vault
  version: 0.30.1
  sourceRef:
    kind: HelmRepository
    name: helm-repo
  interval: 10m0s
  reconcileStrategy: ChartVersion
