---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m0s
  chart:
    spec:
      chart: hashicorp/vault
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: vault
  valuesFrom:
    - kind: ConfigMap
      name: vault-values
      #namespace: vault
      valuesKey: values.yaml
