---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: port-front
  namespace: apps
  labels:
    app: port-front
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - app.newsbro.cc
    secretName: newsbro-wildcard-tls
  rules:
    - host: app.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: port-front
                port:
                  number: 80
