name: repo-account

on:
  push:
    branches: [ "main" ]
    tags: [ 'repo-account-v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/repo-account

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Go Format
        run: go fmt ./...
        working-directory: ./apps/repo-account
      - name: Go Lint
        working-directory: ./apps/repo-account
        run: |
          go vet ./...

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - run: |
          go mod tidy
          go mod download
        working-directory: ./apps/repo-account
      - run: go build -o bin/api src/cmd/main.go
        working-directory: ./apps/repo-account

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - run: go build -o bin/api src/cmd/main.go
        working-directory: ./apps/repo-account
      - name: Start dependencies
        working-directory: ./apps/repo-account
        run: docker compose up -d
      - name: Run API + Tests
        working-directory: ./apps/repo-account
        if: always()
        run: |
          ./bin/api &
          API_PID=$!
          go test -v ./... || true
          kill -9 ${API_PID}
      - name: Stop dependencies
        working-directory: ./apps/repo-account
        run: docker compose down

  build-docker:
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - uses: docker/setup-buildx-action@v3
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,pattern=repo-account-v{{version}}
            type=ref,event=branch
            type=sha
      - id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/repo-account.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
